const products = [
    {
        id:1,
        category:"derby",
        image:"./images/derby/shoe1.jpeg",
        price:370
    },
    {
        id:2,
        category:"derby",
        image:"./images/derby/shoe2.jpeg",
        price:370
    },
    {
        id:3,
        category:"derby",
        image:"./images/derby/shoe3.jpeg",
        price:370
    },
    {
        id:4,
        category:"derby",
        image:"./images/derby/shoe4.jpeg",
        price:370
    },
    {
        id:5,
        category:"derby",
        image:"./images/derby/shoe5.jpeg",
        price:370
    },
    {
        id:6,
        category:"derby",
        image:"../images/derby/shoe6.jpeg",
        price:370
    },
    {
        id:7,
        category:"derby",
        image:"./images/derby/shoe7.jpeg",
        price:370
    },
    {
        id:8,
        category:"derby",
        image:"./images/derby/shoe8.jpeg",
        price:370
    },
    {
        id:9,
        category:"derby",
        image:"./images/derby/shoe9.jpeg",
        price:370
    },
    {
        id:10,
        category:"derby",
        image:"./images/derby/shoe10.jpeg",
        price:370
    },
    {
        id:11,
        category:"derby",
        image:"./images/derby/shoe11.jpeg",
        price:370
    },
    {
        id:12,
        category:"derby",
        image:"./images/derby/shoe12.jpeg",
        price:370
    },
    {
        id:13,
        category:"derby",
        image:"./images/derby/shoe13.jpeg",
        price:370
    },
    {
        id:14,
        category:"derby",
        image:"./images/derby/shoe14.jpeg",
        price:370
    },
    {
        id:15,
        category:"loafer",
        image:"./images/loafer/shoe1.jpeg",
        price:370
    },
    {
        id:16,
        category:"loafer",
        image:"./images/loafer/shoe2.jpeg",
        price:370
    },
    {
        id:17,
        category:"loafer",
        image:"./images/loafer/shoe3.jpeg",
        price:370
    },
    {
        id:18,
        category:"loafer",
        image:"./images/loafer/shoe4.jpeg",
        price:370
    },
    {
        id:19,
        category:"loafer",
        image:"./images/loafer/shoe5.jpeg",
        price:370
    },
    {
        id:20,
        category:"loafer",
        image:"./images/loafer/shoe6.jpeg",
        price:370
    },
    {
        id:21,
        category:"loafer",
        image:"./images/loafer/shoe7.jpeg",
        price:370
    },
    {
        id:22,
        category:"loafer",
        image:"./images/loafer/shoe8.jpeg",
        price:370
    },
    {
        id:23,
        category:"loafer",
        image:"./images/loafer/shoe9.jpeg",
        price:370
    },
    {
        id:24,
        category:"loafer",
        image:"./images/loafer/shoe10.jpeg",
        price:370
    },
    {
        id:25,
        category:"loafer",
        image:"./images/loafer/shoe11.jpeg",
        price:370
    },
    {
        id:26,
        category:"loafer",
        image:"./images/loafer/shoe12.jpeg",
        price:370
    },
    {
        id:27,
        category:"loafer",
        image:"./images/loafer/shoe13.jpeg",
        price:370
    },
    {
        id:28,
        category:"loafer",
        image:"./images/loafer/shoe14.jpeg",
        price:370
    },
]
export default products;